"""Freeze the per-model evaluation walls from the archived cutoff probes.

Applies the ex-ante rule stated in ../README.md §1.5 wall-setting:
    wall = max(reported cutoff, last month with LAP >= 0.5) + 3-month safety margin.
LAP (Gao-Jiang-Yan): P(higher) + P(lower) from the FIRST answer token's top logprobs —
the probability mass the model puts on committing to a direction rather than abstaining.

Uses ONLY probe data (no factor-performance data is touched). Emits ../WALLS.md; the git
commit of that file freezes the walls before any evaluation runs.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

EXP2 = Path(__file__).resolve().parent.parent
CORPUS = EXP2 / "corpus"

REPORTED = {
    "gpt-4-0613": "2021-09",
    "gpt-4o-2024-08-06": "2023-10",
    "gpt-4.1-2025-04-14": "2024-06",
    "meta-llama_Llama-3.3-70B-Instruct-Turbo": "2023-12",
}
MARGIN_MONTHS = 3
LAP_THRESHOLD = 0.5


def add_months(ym: str, k: int) -> str:
    y, m = int(ym[:4]), int(ym[5:7])
    m += k
    y += (m - 1) // 12
    m = (m - 1) % 12 + 1
    return f"{y}-{m:02d}"


def lap_from_response(resp: dict) -> float | None:
    try:
        top = resp["choices"][0]["logprobs"]["content"][0]["top_logprobs"]
    except (KeyError, IndexError, TypeError):
        return None
    p = 0.0
    for t in top:
        tok = t["token"].strip().lower()
        if tok.startswith(("higher", "lower", "high", "low")):
            p += math.exp(t["logprob"])
    return min(p, 1.0)


def main() -> None:
    lines = ["# WALLS.md — frozen per-model evaluation walls (Exp 2)", ""]
    lines.append("*Generated by src/04_freeze_walls.py from the archived probe battery ONLY — no")
    lines.append("factor-performance data touched. Rule (ex ante, README §1.5): wall = max(reported")
    lines.append(f"cutoff, last month with LAP ≥ {LAP_THRESHOLD}) + {MARGIN_MONTHS}-month margin. LAP = P(higher)+P(lower)")
    lines.append("from the first answer token's top-5 logprobs (Gao–Jiang–Yan). The git commit of")
    lines.append("this file freezes the walls; evaluation may only use months STRICTLY AFTER the wall.*")
    lines.append("")

    for model, reported in REPORTED.items():
        pf = CORPUS / model / "probes.jsonl"
        months: dict[str, tuple[float | None, str]] = {}
        for line in pf.read_text().splitlines():
            r = json.loads(line)
            if r["family"] != "index_recall":
                continue
            ym = f"{r['probe_id'][4:8]}-{r['probe_id'][8:10]}"
            lap = lap_from_response(r["response"])
            ans = r["answer"].strip().lower().rstrip(".")
            months[ym] = (lap, ans)

        confident = [ym for ym, (lap, ans) in sorted(months.items())
                     if (lap is not None and lap >= LAP_THRESHOLD)
                     or (lap is None and ans in ("higher", "lower"))]
        last_conf = max(confident) if confident else "none"
        base = max(reported, last_conf) if confident else reported
        wall = add_months(base, MARGIN_MONTHS)

        lines.append(f"## {model}")
        lines.append(f"- reported cutoff: **{reported}**; last month with LAP ≥ {LAP_THRESHOLD}: "
                     f"**{last_conf}**  →  **WALL = {wall}** (evaluation uses months > {wall})")
        battery_end = max(months)
        if reported >= battery_end:
            lines.append(f"- ⚠ battery ends {battery_end} ≤ reported cutoff — wall rests on "
                         f"reported+margin only (bracketing insufficient).")
        lines.append("- LAP by month (· = <0.05):")
        row = []
        for ym, (lap, ans) in sorted(months.items()):
            v = "  · " if (lap is not None and lap < 0.05) else (f"{lap:.2f}" if lap is not None else f"?{ans[:3]}")
            row.append(f"{ym[2:]}:{v}")
        for i in range(0, len(row), 6):
            lines.append("  " + "  ".join(row[i:i + 6]))
        lines.append("")

    lines.append("## Evaluation windows implied (data ends: OSAP 2024-12, JKP ~2025-12, French 2026-05)")
    lines.append("- gpt-4-0613 (wall 2022-04): **2022-05 → 2024-12 on OSAP (32 months)**, longer on JKP/French.")
    lines.append("- gpt-4o-2024-08-06 (wall 2024-01): 2024-02 → 2024-12 on OSAP (11 months), ~23 on JKP.")
    lines.append("- gpt-4.1-2025-04-14 (wall 2025-02): **OSAP window EMPTY** — evaluate on JKP/French only")
    lines.append("  (~10 months); the panel's power rests on gpt-4-0613, as designed.")
    lines.append("")
    lines.append("Noteworthy for the paper: two isolated post-reported-cutoff LAP spikes (gpt-4-0613 at")
    lines.append("2022-01, correct answer; gpt-4.1 at 2024-11) — direct evidence, from our own instrument,")
    lines.append("that effective cutoffs exceed reported ones (Cheng et al.'s caveat, measured here).")

    out = EXP2 / "WALLS.md"
    out.write_text("\n".join(lines) + "\n")
    print("wrote WALLS.md")


if __name__ == "__main__":
    main()
